In [1]:
import pandas as pd
import json
import requests
import matplotlib.pyplot as plt

In [ ]:
#Norfolk
#url= 'https://data.norfolk.gov/resource/vfm4-5wv6.json'

# Make request and store response
#response = requests.get(url)

# Storing the JSON response within a variable
#norfolk_data = response.json()
# Use json.dumps to print the json
#print(json.dumps(norfolk_data, indent=4, sort_keys=True))

# Convert to DataFrame
#norfolk_df = pd.DataFrame(norfolk_data)

In [18]:
# Check link for csv file: https://data.norfolk.gov/Government/Norfolk-Animal-Care-and-Adoption-Center-NACC-/vfm4-5wv6
adoption= "Norfolk_Animal.csv"
adoption= pd.read_csv(adoption)
adoption.head()
adoption.shape
#adoption.dtypes

(29276, 21)

In [20]:
#Converting Intake Date and Outcome Date to pandas date format
adoption['Intake Date'] = pd.to_datetime(adoption['Intake Date'],format='%m/%d/%Y')
adoption['Outcome Date'] = pd.to_datetime(adoption['Outcome Date'],format='%m/%d/%Y')

#adoption.shape
#adoption.dtypes
adoption

,Animal ID,Animal Name,Animal Type,Sex,Years Old,Months Old,Primary Breed,Primary Color,Tag Number,Intake Date,...,Intake Subtype,Outcome Type,Outcome Subtype,Outcome Date,Intake Month,Intake Day of the Week,Intake Year,Outcome Month,Outcome Day of the Week,Outcome Year
0,A000455,SNOWBALL,Dog,Neutered Male,4.0,0.00,POODLE MIN,WHITE,L17-011989,2017-08-16,...,Over the Counter,Adoption,Walk-In,2017-08-19,NaN,NaN,NaN,NaN,NaN,NaN
1,A000455,SNOWBALL,Dog,Neutered Male,4.0,0.00,POODLE MIN,WHITE,L17-011502,2017-05-03,...,Over the Counter,Adoption,Walk-In,2017-05-13,NaN,NaN,NaN,NaN,NaN,NaN
2,A000601,SHEILA E,Cat,Spayed Female,0.0,1.80,DOMESTIC SH,CALICO,L16-010051,2016-08-20,...,Transfer,Adoption,Website Information,2016-10-02,NaN,NaN,NaN,NaN,NaN,NaN
3,A001474,CHARLES,Dog,Neutered Male,1.0,0.00,LABRADOR RETR,YELLOW,NaN,2017-04-27,...,Over the Counter,Return to Owner,Walk-In,2017-06-06,NaN,NaN,NaN,NaN,NaN,NaN
4,A001474,CHARLES,Dog,Neutered Male,1.0,0.00,LABRADOR RETR,YELLOW,L16-009301,2016-03-30,...,Animal Cruelty,Return to Owner,NaN,2016-04-15,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29271,A059219,OZZY,Dog,Male,NaN,NaN,MASTIFF,RED,981020039165640,2020-11-22,...,Over the Counter,Adoption,Walk-In,2020-11-25,NaN,NaN,NaN,NaN,NaN,NaN
29272,A059228,NaN,Cat,Neutered Male,8.0,NaN,DOMESTIC SH,ORG TABBY,NaN,2020-11-23,...,Animal Cruelty,Disposal of Deceased Pet,NaN,2020-11-23,NaN,NaN,NaN,NaN,NaN,NaN
29273,A059254,NaN,Cat,Female,NaN,1.85,DOMESTIC SH,ORG TABBY,NaN,2020-11-27,...,Animal Control,Foster,Underage or Underweight,2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN
29274,A059260,CHOCOLATE,Dog,Male,2.0,NaN,POODLE TOY,BROWN,985112001208056,2020-11-29,...,Animal Control,Return to Owner,Walk-In,2020-11-29,NaN,NaN,NaN,NaN,NaN,NaN
29275,A059267,NaN,Other,Unknown,3.0,NaN,RACCOON,TRICOLOR,NaN,2020-11-29,...,Animal Control,Euthanized,Wildlife,2020-11-29,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#Pulling only the columns with outcome type as adoption
adoption= adoption.loc[adoption['Outcome Type'] == 'Adoption']
adoption
#adoption.dtypes

,Animal ID,Animal Name,Animal Type,Sex,Years Old,Months Old,Primary Breed,Primary Color,Tag Number,Intake Date,...,Intake Subtype,Outcome Type,Outcome Subtype,Outcome Date,Intake Month,Intake Day of the Week,Intake Year,Outcome Month,Outcome Day of the Week,Outcome Year
0,A000455,SNOWBALL,Dog,Neutered Male,4.0,0.0,POODLE MIN,WHITE,L17-011989,2017-08-16,...,Over the Counter,Adoption,Walk-In,2017-08-19,NaN,NaN,NaN,NaN,NaN,NaN
1,A000455,SNOWBALL,Dog,Neutered Male,4.0,0.0,POODLE MIN,WHITE,L17-011502,2017-05-03,...,Over the Counter,Adoption,Walk-In,2017-05-13,NaN,NaN,NaN,NaN,NaN,NaN
2,A000601,SHEILA E,Cat,Spayed Female,0.0,1.8,DOMESTIC SH,CALICO,L16-010051,2016-08-20,...,Transfer,Adoption,Website Information,2016-10-02,NaN,NaN,NaN,NaN,NaN,NaN
17,A002987,ENZO,Dog,Neutered Male,1.0,0.0,PIT BULL,BLACK,L17-011517,2017-04-30,...,Over the Counter,Adoption,Walk-In,2017-05-16,NaN,NaN,NaN,NaN,NaN,NaN
28,A006357,SKIPPY,Dog,Neutered Male,5.0,0.0,BEAGLE,TRICOLOR,982000123128327,2016-05-03,...,Over the Counter,Adoption,NaN,2016-05-18,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29257,A059140,SARAH,Cat,Neutered Male,1.0,4.0,DOMESTIC SH,BRN TABBY,982126056569270,2020-11-14,...,Transfer,Adoption,Walk-In,2020-11-16,NaN,NaN,NaN,NaN,NaN,NaN
29258,A059142,NaN,Dog,Male,NaN,6.0,GERM SHEPHERD,TAN,981020039171781,2020-11-14,...,Animal Control,Adoption,NaN,2020-11-28,NaN,NaN,NaN,NaN,NaN,NaN
29265,A059175,NaN,Dog,Spayed Female,1.0,NaN,PIT BULL,BR BRINDLE,981020039180182,2020-11-19,...,Animal Control,Adoption,Walk-In,2020-11-25,NaN,NaN,NaN,NaN,NaN,NaN
29270,A059217,DODGE,Dog,Male,NaN,1.9,PIT BULL,TAN,981020039180052,2020-11-21,...,Animal Control,Adoption,Website Information,2020-11-27,NaN,NaN,NaN,NaN,NaN,NaN
29271,A059219,OZZY,Dog,Male,NaN,NaN,MASTIFF,RED,981020039165640,2020-11-22,...,Over the Counter,Adoption,Walk-In,2020-11-25,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
#Adding outcome month and outcome year as additional columns
adoption['Outcome Month'] = adoption['Outcome Date'].map(lambda x: x.strftime('%m'))
adoption['Outcome Year'] = adoption['Outcome Date'].map(lambda x: x.strftime('%Y'))
adoption

,Animal ID,Animal Name,Animal Type,Sex,Years Old,Months Old,Primary Breed,Primary Color,Tag Number,Intake Date,...,Intake Subtype,Outcome Type,Outcome Subtype,Outcome Date,Intake Month,Intake Day of the Week,Intake Year,Outcome Month,Outcome Day of the Week,Outcome Year
0,A000455,SNOWBALL,Dog,Neutered Male,4.0,0.0,POODLE MIN,WHITE,L17-011989,2017-08-16,...,Over the Counter,Adoption,Walk-In,2017-08-19,NaN,NaN,NaN,08,NaN,2017
1,A000455,SNOWBALL,Dog,Neutered Male,4.0,0.0,POODLE MIN,WHITE,L17-011502,2017-05-03,...,Over the Counter,Adoption,Walk-In,2017-05-13,NaN,NaN,NaN,05,NaN,2017
2,A000601,SHEILA E,Cat,Spayed Female,0.0,1.8,DOMESTIC SH,CALICO,L16-010051,2016-08-20,...,Transfer,Adoption,Website Information,2016-10-02,NaN,NaN,NaN,10,NaN,2016
17,A002987,ENZO,Dog,Neutered Male,1.0,0.0,PIT BULL,BLACK,L17-011517,2017-04-30,...,Over the Counter,Adoption,Walk-In,2017-05-16,NaN,NaN,NaN,05,NaN,2017
28,A006357,SKIPPY,Dog,Neutered Male,5.0,0.0,BEAGLE,TRICOLOR,982000123128327,2016-05-03,...,Over the Counter,Adoption,NaN,2016-05-18,NaN,NaN,NaN,05,NaN,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29257,A059140,SARAH,Cat,Neutered Male,1.0,4.0,DOMESTIC SH,BRN TABBY,982126056569270,2020-11-14,...,Transfer,Adoption,Walk-In,2020-11-16,NaN,NaN,NaN,11,NaN,2020
29258,A059142,NaN,Dog,Male,NaN,6.0,GERM SHEPHERD,TAN,981020039171781,2020-11-14,...,Animal Control,Adoption,NaN,2020-11-28,NaN,NaN,NaN,11,NaN,2020
29265,A059175,NaN,Dog,Spayed Female,1.0,NaN,PIT BULL,BR BRINDLE,981020039180182,2020-11-19,...,Animal Control,Adoption,Walk-In,2020-11-25,NaN,NaN,NaN,11,NaN,2020
29270,A059217,DODGE,Dog,Male,NaN,1.9,PIT BULL,TAN,981020039180052,2020-11-21,...,Animal Control,Adoption,Website Information,2020-11-27,NaN,NaN,NaN,11,NaN,2020
29271,A059219,OZZY,Dog,Male,NaN,NaN,MASTIFF,RED,981020039165640,2020-11-22,...,Over the Counter,Adoption,Walk-In,2020-11-25,NaN,NaN,NaN,11,NaN,2020

In [16]:
#Pulling out only the columns relevant for our research
norfolk_df= adoption[["Animal ID","Animal Type","Sex", "Years Old","Months Old","Primary Breed", "Primary Color","Intake Type","Intake Date","Outcome Type","Outcome Date","Outcome Month","Outcome Year"]]
norfolk_df

,Animal ID,Animal Type,Sex,Years Old,Months Old,Primary Breed,Primary Color,Intake Type,Intake Date,Outcome Type,Outcome Date,Outcome Month,Outcome Year
0,A000455,Dog,Neutered Male,4.0,0.0,POODLE MIN,WHITE,Return,2017-08-16,Adoption,2017-08-19,08,2017
1,A000455,Dog,Neutered Male,4.0,0.0,POODLE MIN,WHITE,Owner Surrendered,2017-05-03,Adoption,2017-05-13,05,2017
2,A000601,Cat,Spayed Female,0.0,1.8,DOMESTIC SH,CALICO,Transfer,2016-08-20,Adoption,2016-10-02,10,2016
17,A002987,Dog,Neutered Male,1.0,0.0,PIT BULL,BLACK,Stray,2017-04-30,Adoption,2017-05-16,05,2017
28,A006357,Dog,Neutered Male,5.0,0.0,BEAGLE,TRICOLOR,Owner Surrendered,2016-05-03,Adoption,2016-05-18,05,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29257,A059140,Cat,Neutered Male,1.0,4.0,DOMESTIC SH,BRN TABBY,Transfer,2020-11-14,Adoption,2020-11-16,11,2020
29258,A059142,Dog,Male,NaN,6.0,GERM SHEPHERD,TAN,Stray,2020-11-14,Adoption,2020-11-28,11,2020
29265,A059175,Dog,Spayed Female,1.0,NaN,PIT BULL,BR BRINDLE,Stray,2020-11-19,Adoption,2020-11-25,11,2020
29270,A059217,Dog,Male,NaN,1.9,PIT BULL,TAN,Stray,2020-11-21,Adoption,2020-11-27,11,2020
29271,A059219,Dog,Male,NaN,NaN,MASTIFF,RED,Owner Surrendered,2020-11-22,Adoption,2020-11-25,11,2020

In [ ]:
# URL for GET requests to retrieve COVID data
url = " https://api.covidtracking.com/v1/states/current.json"

# Make a request and store response
response = requests.get(url)

# Print status code - data is good
print(response.status_code)

In [ ]:
# Retrieving data and converting it into JSON
requests.get(url).json()

data = response.json()
print(json.dumps(data, indent=4))

In [ ]:
# It is possible to grab a specific value 
# from within the JSON object
print(data[0]["state"])